on: [pull_request]

jobs:
  go_mod_tidy_job:
    runs-on: ubuntu-latest
    name: Install golang
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - run: go version
      - uses: actions/checkout@v3
        with: 
          repository: supertokens/supertokens-golang
          ref: master

    